# Generated by Django 5.0 on 2023-12-19 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField()),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("specification", models.TextField(blank=True)),
                ("slug", models.TextField()),
                (
                    "label",
                    models.CharField(
                        choices=[("new", "new"), ("sale", "sale"), ("hot", "hot")],
                        max_length=20,
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
    ]
